# Generated by Django 4.1.3 on 2023-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.DeleteModel(
            name='productImages',
        ),
    ]
