# Generated by Django 4.1.3 on 2023-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cart_user_alter_order_status_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
