# Generated by Django 4.1.3 on 2023-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_discount_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
